# Site settings
title: The Bitcoin Association of Hong Kong
location: Hong Kong
description: "Fostering and promoting Bitcoin and its technology in Hong Kong."
baseurl: ""
url: "https://www.bitcoinhk.org"


future: true





# podcast stuff

podcast_url: https://www.bitcoinhk.org/podcast/
podcast_album_art: /images/bahk-logo-big-podcast.png
podcast_title: The Bitcoin Lecture Series
podcast_owner: The Bitcoin Association of Hong Kong
podcast_email: info@bitcoinhk.org
podcast_category: Technology
podcast_subcategory_one:
podcast_subcategory_two:
podcast_explicit: "no"
podcast_author: The Bitcoin Association of Hong Kong
podcast_description: The talks and panels at events held by the Bitcoin Association of Hong Kong
podcast_summary: The Bitcoin Lecture Series is a series of podcasts and videos sharing the talks and panels at events held by the Bitcoin Association of Hong Kong with the global Bitcoin and blockchain communities.
podcast_subtitle: Join us in learning more about Bitcoin and blockchain!





# More settings
accent: "#E74C3C"
github: "bitcoinhk/bitcoinhk.github.io"
contact: "info@bitcoinhk.org"
organizers: "The Community"
email: "info@bitcoinhk.org"

# Get Meetup Notifications, visible or hidden
notifications: "visible"


# Build settings
markdown: kramdown
permalink: pretty

timezone: Asia/Hong_Kong

gems:
  - jekyll-redirect-from

prose:
  rooturl: '_posts'
  siteurl: 'https://www.bitcoinhk.org/'
  media: 'media'
  ignore:
    - index.html
    - meetups.html
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "select"
          options:
            - name: 'meetup'
              value: 'meetup'
            - name: 'blog'
              value: 'blog'
      - name: "author"
        field:
          element: "text"
          label: "Author (Passcard w/ leading +)"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "date"
        field:
          element: "text"
          label: "Date (YYYY-MM-DD HH:MM:SS)"
          value: "2014-06-08 10:30:00"
      - name: "host"
        field:
          element: "text"
          label: "Host"
          value: ""
      - name: "address"
        field:
          element: "text"
          label: "Address"
          value: ""
      - name: "link"
        field:
          element: "text"
          label: "Link to RSVP site (Meetup.com, etc)"
          value: ""
      - name: "background"
        field:
          element: "text"
          label: "Background (CSS)"
          value: "url() #FF0000"
